### ISSUE TITLE
Implement `test_get_cents()`

### ISSUE THREAD

**Issue by hammadmajid** [hammadmajid/algorithms#13]
**Describe the solution you'd like**

Implement `get_cents()` test as `test_get_cents()` in `src/test/app_test.cc`

When called `get_cents()` method should output `Change owed: ` on console and then prompt the user for input.

Provide the `get_cents()` method with following inputs:
1. `1` should return `100`
2. `3.5` should return `350`
3. `73.2696` should return `7327`
4.  Any character other than 0-9 should be rejected

**Additional context**
If the input is invalid than re-prompt the user for input

**The `get_cents()` method in `src/app/user.cc`**

```cpp
int greedy_algorithm::get_cents() 
 { 
     float change = 0; 
  
     while (true) 
     { 
         std::cout << std::endl 
                   << "Change owed: "; 
  
         std::cin >> change; 
  
         if(std::cin.fail()) 
         { 
             //Tells user that their input was incorrect, then clears the stream for  
             //another attempt until user inputs correct information 
             std::cout << "You've enter an incorrect input" << std::endl; 
  
             std::cin.clear(); 
             std::cin.ignore(__INT_MAX__, '\n'); 
         } 
  
         if (change > 0) 
         { 
             break; 
         } 
     } 
  
     return round(change * 100); 
 }
```

**Comment by HappyBirdisAXE** [comment]
Do you wish to have `test_get_cents() ` test the input or am I misunderstanding it?

**Comment by hammadmajid** [comment]
Test input.
Using the `cassert` library

```cpp
int test_get_cents()
{
    assert(/* logic here */);
    // Exit with non-zero code if assert fails
}
```

**Comment by HappyBirdisAXE** [comment]
Ah okay, got it.

**Comment by HappyBirdisAXE** [comment]
There's are problems with <cassert>, we can use <assert.h> however. Do you mind the differences or is that all good?
Here's an forum on the discussion:
https://stackoverflow.com/questions/10625716/in-what-cases-we-need-to-include-cassert

**Comment by hammadmajid** [comment]
I don't see a problem in using `assert.h`.

Just don't use `using namespace` directive. It will definitely pollute the namespace.

**Comment by hammadmajid** [comment]
Also, follow this style guide:

https://google.github.io/styleguide/cppguide.html

**Comment by HappyBirdisAXE** [comment]
I have everything set up, however should I be testing for the final result that comes for `get_cents` or test for the input within the function?

**Comment by hammadmajid** [comment]
Test the return value for these cases:

> 1. `1` should return `100`
> 2. `3.5` should return `350`
> 3. `73.2696` should return `7327`

Test within the function for this case:

> 4.  Any character other than 0-9 should be rejected

**Comment by HappyBirdisAXE** [comment]
Oh okay, my bad, misunderstood on my end.
